name: Create ALF File

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        unity-version: [2018.4.9f1, 2019.2.5f1]
    container: docker://gableroux/unity3d:${{ matrix.unity-version }}-webgl
    
    steps:
    - name: Create Manual Activation File
      run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -logfile -createManualActivationFile || exit 0
    - name: Copy To Artifact
      run: |
        mkdir artifact
        cp Unity_v${{ matrix.unity-version }}.alf artifact
    - uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.unity-version }}
        path: artifact
