name: Create ALF File

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        unity-version:
        - 2020.1.3f1
    
    steps:
    - uses: pCYSl5EDgo/setup-unity@master
      with:
        unity-version: ${{ matrix.unity-version }}
    - name: Create Manual Activation File
      run: /opt/Unity/Editor/Unity -batchmode -nographics -manualActivation -logFile /dev/stdout -username ${USERNAME} -password ${PASSWORD} || exit 0
      env:
        USERNAME: ${{ secrets.username }} 
        PASSWORD: ${{ secrets.password }} 
    - uses: actions/upload-artifact@v1
      with:
        name: Unity_v${{ matrix.unity-version }}.alf
        path: ./Unity_v${{ matrix.unity-version }}.alf
